/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import clases.Datos;
import clases.Producto;
import clases.Utilidades;
import javax.swing.JOptionPane;

/**
 *
 * @author leandraroque
 */
public class frmProductos extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmUsuarios
     */
    public frmProductos() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtIDProducto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        txtConsultar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtNotas = new javax.swing.JTextArea();

        jButton1.setText("jButton1");

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jLabel1.setFont(new java.awt.Font("Oswald", 0, 14)); // NOI18N
        jLabel1.setText("IDProducto");

        txtIDProducto.setText("lea");
        txtIDProducto.setActionCommand("<Not Set>");

        jLabel3.setFont(new java.awt.Font("Oswald", 0, 14)); // NOI18N
        jLabel3.setText("Descripción");

        txtDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescripcionActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Oswald", 0, 14)); // NOI18N
        jLabel4.setText("Notas");

        txtConsultar.setText("Consultar");
        txtConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConsultarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnNuevo.setText("Nuevo");
        btnNuevo.setToolTipText("");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.setToolTipText("");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnBorrar.setText("Borrar");
        btnBorrar.setToolTipText("");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Oswald", 0, 14)); // NOI18N
        jLabel5.setText("Precio");

        txtNotas.setColumns(20);
        txtNotas.setRows(5);
        jScrollPane1.setViewportView(txtNotas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(79, 79, 79)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(jLabel1)
                                                                                .addGap(18, 18, 18))
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(jLabel4)
                                                                                        .addComponent(jLabel5))
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jLabel3)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(txtIDProducto)
                                                        .addComponent(txtPrecio)
                                                        .addComponent(txtDescripcion)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                .addGap(6, 6, 6)
                                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(53, 53, 53)
                                                .addComponent(txtConsultar)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(btnLimpiar)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(btnNuevo)
                                                .addGap(12, 12, 12)
                                                .addComponent(btnModificar)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnBorrar)))
                                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtIDProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addGap(0, 11, Short.MAX_VALUE))
                                        .addComponent(txtPrecio))
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btnModificar, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                                        .addComponent(btnBorrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtConsultar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
        );

        pack();
    }// </editor-fold>

    private void txtConsultarActionPerformed(java.awt.event.ActionEvent evt) {
        String idProducto =txtIDProducto.getText();
        if(idProducto.equals("")){
            JOptionPane.showMessageDialog(this,"Debe ingresas IdProducto");
            return;
        }
        Datos misDatos = new Datos();
        Producto miProducto =misDatos.getProducto(idProducto);

        if(miProducto == null){
            JOptionPane.showMessageDialog(this,"Producto no existe");
            misDatos.cerrarConexion();
            return;
        }
        misDatos.cerrarConexion();
        txtDescripcion.setText(miProducto.getDescripcion());
        txtPrecio.setText(""+ miProducto.getPrecio());
        txtNotas.setText(miProducto.getNotas());


    }

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {
        txtIDProducto.setText("");
        txtDescripcion.setText("");
        txtDescripcion.setText("");
        txtPrecio.setText("");
        txtNotas.setText("");

    }

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {
        String idProducto = txtIDProducto.getText();
        if(idProducto.equals("")) {
            JOptionPane.showMessageDialog(this,"Debe ingresar IdUsuario");
            return;
        }
        Datos misDatos = new Datos();
        Producto miProducto = misDatos.getProducto(idProducto);

        if(miProducto != null) {
            JOptionPane.showMessageDialog(this,"Usuario ya existe");
            misDatos.cerrarConexion();
            return;
        }


        String descripcion =txtDescripcion.getText();
        if(descripcion.equals("")){
            JOptionPane.showMessageDialog(this,"Debe de ingresar el nombre");
            return;
        }

        if(txtPrecio.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Debe de ingresar los apellidos");
            return;
        }

        if(!Utilidades.isNumeric(txtPrecio.getText())){
            JOptionPane.showMessageDialog(this,"Debe de ingresar los apellidos");
            return;
        }
        int precio = Integer.parseInt(txtPrecio.getText());
        if(precio <= 0){
            JOptionPane.showMessageDialog(this,"Debe de ingresar los apellidos");
            return;
        }

        String notas =txtNotas.getText();
        if(notas.equals("")){
            JOptionPane.showMessageDialog(this,"Debe de ingresar los apellidos");
            return;
        }

        miProducto = new Producto(
                idProducto,
                descripcion,
                precio,
                notas);
        if(misDatos.newProducto(miProducto)){
            JOptionPane.showMessageDialog(this,"Listo!");

        }else{
            JOptionPane.showMessageDialog(this,"No creado");

        }
        misDatos.cerrarConexion();

    }

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {
        String idProducto = txtIDProducto.getText();
        if(idProducto.equals("")) {
            JOptionPane.showMessageDialog(this,"Debe ingresar IdUsuario");
            return;
        }
        Datos misDatos = new Datos();
        Producto miProducto = misDatos.getProducto(idProducto);

        if(miProducto == null) {
            JOptionPane.showMessageDialog(this,"Usuario no existe");
            misDatos.cerrarConexion();
            return;
        }


        String descripcion =txtDescripcion.getText();
        if(descripcion.equals("")){
            JOptionPane.showMessageDialog(this,"Debe de ingresar el nombre");
            return;
        }
        int precio = 0;
        if(txtPrecio.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Debe de ingresar los apellidos");
            return;
        }

        if(!Utilidades.isNumeric(txtPrecio.getText())){
            JOptionPane.showMessageDialog(this,"Debe de ingresar los apellidos");
            return;
        }

        if(precio <= 0){
            JOptionPane.showMessageDialog(this,"Debe de ingresar los apellidos");
            return;
        }

        String notas =txtNotas.getText();
        if(notas.equals("")){
            JOptionPane.showMessageDialog(this,"Debe de ingresar los apellidos");
            return;
        }

        miProducto = new Producto(
                idProducto,
                descripcion,
                precio,
                notas);
        if(misDatos.updateProducto(miProducto)){
            JOptionPane.showMessageDialog(this,"Actualizado!");

        }else{
            JOptionPane.showMessageDialog(this,"No actualizado");

        }
        misDatos.cerrarConexion();
    }

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {
        String idProducto = txtIDProducto.getText();
        if(idProducto.equals("")) {
            JOptionPane.showMessageDialog(this,"Debe ingresar IdUsuario");
            return;
        }
        Datos misDatos = new Datos();
        Producto miProducto = misDatos.getProducto(idProducto);

        if(miProducto == null) {
            JOptionPane.showMessageDialog(this,"Usuario no existe");
            misDatos.cerrarConexion();
            return;
        }


        int rta = JOptionPane.showConfirmDialog(rootPane, "Esta seguro de "
                + "borrar el registro");
        if(rta != 0){
            return;
        }
        if(misDatos.deleteProducto(miProducto)){
            JOptionPane.showMessageDialog(this,"Registro borrado");
            btnLimpiarActionPerformed(evt);

        }else{
            JOptionPane.showMessageDialog(this,"Registro no borrado");

        }
        misDatos.cerrarConexion();
    }

    private void txtDescripcionActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }





    // Variables declaration - do not modify
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton txtConsultar;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtIDProducto;
    private javax.swing.JTextArea txtNotas;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration
}
